# Sowing Success: How Machine Learning Helps Farmers Select the Best Crops

![Farmer in a field](farmer_in_a_field.jpg)

Measuring essential soil metrics such as nitrogen, phosphorous, potassium levels, and pH value is an important aspect of assessing soil condition. However, it can be an expensive and time-consuming process, which can cause farmers to prioritize which metrics to measure based on their budget constraints.

Farmers have various options when it comes to deciding which crop to plant each season. Their primary objective is to maximize the yield of their crops, taking into account different factors. One crucial factor that affects crop growth is the condition of the soil in the field, which can be assessed by measuring basic elements such as nitrogen and potassium levels. Each crop has an ideal soil condition that ensures optimal growth and maximum yield.

A farmer reached out to you as a machine learning expert for assistance in selecting the best crop for his field. They've provided you with a dataset called `soil_measures.csv`, which contains:

- `"N"`: Nitrogen content ratio in the soil
- `"P"`: Phosphorous content ratio in the soil
- `"K"`: Potassium content ratio in the soil
- `"pH"` value of the soil
- `"crop"`: categorical values that contain various crops (target variable).

Each row in this dataset represents various measures of the soil in a particular field. Based on these measurements, the crop specified in the `"crop"` column is the optimal choice for that field.  

In this project, you will build multi-class classification models to predict the type of `"crop"` and identify the single most importance feature for predictive performance.

In [21]:
# All required libraries are imported here for you.
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

# Load the dataset
crops = pd.read_csv("soil_measures.csv")

# Write your code here

In [22]:
crops.head()

N   P   K        ph  crop
0  90  42  43  6.502985  rice
1  85  58  41  7.038096  rice
2  60  55  44  7.840207  rice
3  74  35  40  6.980401  rice
4  78  42  42  7.628473  rice

In [23]:
crops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   N       2200 non-null   int64  
 1   P       2200 non-null   int64  
 2   K       2200 non-null   int64  
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   object 
dtypes: float64(1), int64(3), object(1)
memory usage: 86.1+ KB


In [24]:
crops.describe()

N            P            K           ph
count  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091     6.469480
std      36.917334    32.985883    50.647931     0.773938
min       0.000000     5.000000     5.000000     3.504752
25%      21.000000    28.000000    20.000000     5.971693
50%      37.000000    51.000000    32.000000     6.425045
75%      84.250000    68.000000    49.000000     6.923643
max     140.000000   145.000000   205.000000     9.935091

In [25]:
#checking the crop types
print(crops["crop"].unique())

['rice' 'maize' 'chickpea' 'kidneybeans' 'pigeonpeas' 'mothbeans'
 'mungbean' 'blackgram' 'lentil' 'pomegranate' 'banana' 'mango' 'grapes'
 'watermelon' 'muskmelon' 'apple' 'orange' 'papaya' 'coconut' 'cotton'
 'jute' 'coffee']


In [26]:
#Creating the data in the form of X (feature variables),y(target values) 
X = crops.drop(["crop"],axis = 1).values
y = crops["crop"].values
print(X)
print(y)

[[ 90.          42.          43.           6.50298529]
 [ 85.          58.          41.           7.03809636]
 [ 60.          55.          44.           7.84020714]
 ...
 [118.          33.          30.           6.36260785]
 [117.          32.          34.           6.75879255]
 [104.          18.          30.           6.77983261]]
['rice' 'rice' 'rice' ... 'coffee' 'coffee' 'coffee']


In [27]:
# splitting the data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state= 42)

In [28]:
print(X_train)

[[ 81.          16.          45.           6.72746816]
 [ 31.         136.         197.           5.65377606]
 [  3.          63.          16.           6.86888171]
 ...
 [ 11.          36.          31.           6.47544932]
 [ 11.         124.         204.           6.36114111]
 [ 32.          78.          22.           7.00703752]]


In [29]:
print(X_train[:,0])

[81. 31.  3. ... 11. 11. 32.]


In [30]:
feature_predictive_performance = {"N":0,"P":1,"K":2,"ph":3}

for key,value in feature_predictive_performance.items():
    #accessing the training data for each feature variable
    # 0 - N, 1-P,2-K,3-ph
    #reshaping the training data to avoid errors from model
    X_train_i = X_train[:,value].reshape(-1,1)
    X_test_i = X_test[:,value].reshape(-1,1) 
    # defining the classifier model - logistic regression from sklearn
    logreg = LogisticRegression()
    #training the model using the features variable
    logreg.fit(X_train_i,y_train)
    #predicting the values using the test set
    y_pred = logreg.predict(X_test_i)
    #evaluating the model using the model using the f1_score
    feature_predictive_performance[key] = metrics.f1_score(y_test,y_pred,average="weighted")
print(feature_predictive_performance)
    
    


{'N': 0.09450469595706455, 'P': 0.12085630781517222, 'K': 0.21829197602087558, 'ph': 0.06945986006231723}


In [31]:
best_predictive_feature = {"K":0.21829197602087558}